@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@slug = my-question-title
@questionId = {{list_questions.response.body.questions[0].id}}
@answerId = 0b18be3b-dee3-42f7-862e-c8c1db1acf71

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "name": "John Doe",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "My Question Title",
  "content": "This is the content of my question."
}

###

# @name list_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/{{slug}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
PUT {{baseUrl}}/questions/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Question Edited",
  "content": "This is the edited content of my question."
}

###

# @name delete_question
DELETE {{baseUrl}}/questions/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST {{baseUrl}}/questions/{{questionId}}/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "This is an answer to the question."
}

###

# @name edit_answer
PUT {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "This is an edited answer to the question."
}

###

# @name delete_answer
DELETE  {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}