@baseUrl = http://localhost:3000
@userId = {{list_users.response.body.users[0].id}}

### Cria um usuário
# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Tiago Lopes",
  "email": "teste@gmail.com",
  "password": "123456"
}

### Busca todos os usuários
# @name list_users
GET {{baseUrl}}/users

### Busca por id
# @name get_user_by_id
GET {{baseUrl}}/users/{{userId}}

### Atualiza um usuário
# @name update_user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Tiago Tavares Lopes",
  "email": "teste@gmail.com",
  "password": "123456"
}

### Deleta um usuário
# @name delete_user
DELETE {{baseUrl}}/users/{{userId}}