@baseUrl = http://localhost:3000
@messageId = {{list_messages.response.body.messages[0].id}}
@userId = {{list_users.response.body.users[0].id}}

### Cria uma mensagem
# @name create_message
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "Mensagem aqui",
  "from": "Tiago Lopes",
  "to": "Joana",
  "read": true
}

### Busca todas as mensagens
# @name list_messages
GET {{baseUrl}}/messages

### Busca mensagem por id
# @name get_message_by_id
GET {{baseUrl}}/messages/{{messageId}}

### Atualiza uma mensagem
# @name update_message
PUT {{baseUrl}}/messages/{{messageId}}
Content-Type: application/json

{
  "text": "Mensagem aqui",
  "from": "Tiago Lopes",
  "to": "Joana Santos",
  "read": true
}

### Deleta uma mensagem
# @name delete_message
DELETE {{baseUrl}}/messages/{{messageId}}

### Cria um usuário
# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Tiago Lopes",
  "email": "teste@gmail.com",
  "password": "123456"
}

### Busca todos os usuários
# @name list_users
GET {{baseUrl}}/users

### Busca por id
# @name get_user_by_id
GET {{baseUrl}}/users/{{userId}}

### Atualiza um usuário
# @name update_user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Tiago Tavares Lopes",
  "email": "teste@gmail.com",
  "password": "123456"
}

### Deleta um usuário
# @name delete_user
DELETE {{baseUrl}}/users/{{userId}}